name: Generate release artefact

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17"
